# Base Image
FROM node:alpine

# Setting in working directory in container
WORKDIR /app

# Install and copy dependencies
COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

CMD ["npm", "start"]
