apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: subneter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AlexanderLaaser/Subneter.io.git
    targetRevision: main
    path: subneterChart
  destination:
    server: https://kubernetes.default.svc
    namespace: subneter
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
