apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: subneter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AlexanderLaaser/Subneter.io.git
    targetRevision: HEAD
    path: feature/imagepipe
  destination:
    server: https://kubernetes.default.svc
    namespace: subneter
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
