apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.app.name }}-secretproviderclass
  namespace: {{ .Values.app.name }}
spec:
  provider: azure
  secretObjects:
    - secretName: subnetercert
      type: kubernetes.io/tls
      data: 
        - objectName: subnetercert
          key: tls.key
        - objectName: subnetercert
          key: tls.crt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ $.Values.secretprovider.managedidentityid }}
    keyvaultName: {{ $.Values.secretprovider.keyvaultname }}
    tenantId: {{ $.Values.app.tenantid }}
    objects: |
      array:
        - |
          objectName: subnetercert
          objectType: secret              
