apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.app.name }}-secretproviderclass
  namespace: {{ .Values.app.name }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ $.Values.secretprovider.managedIdentityid }}
    keyvaultName: {{ $.Values.secretprovider.keyvaultName }} # Set to the name of your key vault
    tenantId: {{ $.Values.app.tenantId }}
    objects: |
      array:
        - |
          objectName: subneter
          objectType: certificate              
          objectVersion: ""