apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.django.name }}-deployment
  namespace: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.django.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.django.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.django.name }}
    spec:
      containers:
        - name: {{ .Values.django.name }}
          image: "{{ .Values.django.image.repository }}:{{ .Values.django.image.tag }}"
          ports:
            - containerPort: {{ .Values.django.containerPort }}