apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.react.name }}-deployment
  namespace: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.react.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.react.name }}
          image: "{{ .Values.react.image.repository }}:{{ .Values.react.image.tag }}"
          ports:
            - containerPort: {{ .Values.react.containerPort }}
          env:
          - name: VITE_API_SERVER_URL
            valueFrom:
              configMapKeyRef:
                name: frontend-config
                key: VITE_API_SERVER_URL
