apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.django.name }}-service
  namespace: {{ .Values.app.name }}
spec:
  type: {{ .Values.django.service.type }}
  ports:
    - port: {{ .Values.django.service.port }}
      targetPort: {{ .Values.django.containerPort }}
  selector:
    app: {{ .Values.django.name }}