apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.react.name }}-service
spec:
  type: {{ .Values.react.service.type }}
  ports:
    - port: {{ .Values.react.service.port }}
      targetPort: {{ .Values.react.containerPort }}
      protocol: TCP
      name: frontend
  selector:
    app: {{ .Values.react.name }}