app:
  name: subneter
  tenantid: f1640c14-f2cd-4607-b90a-ec03d1b46437
flask:
  name: flask-backend
  replicaCount: 1
  image:
    repository:  acrsubneterdev.azurecr.io/flask
    tag: latest
  containerPort: 5000
  service: 
    type: ClusterIP
    port: 80
react:
  name: react-frontend
  replicaCount: 1
  image:
    repository: acrsubneterdev.azurecr.io/react
    tag: latest
  containerPort: 5173
  service: 
    type: ClusterIP
    port: 80
secretprovider:
  managedidentityid: ca962ecb-4ff2-4e75-8d80-9741378e307c
  keyvaultname: kv-subneterdev