flask:
  name: flask-backend
  replicaCount: 1
  image:
    repository:  acrsubneterdev.azurecr.io/flask
    tag: latest
  containerPort: 5000
  service: 
    type: ClusterIP
    port: 5000
react:
  name: react-frontend
  replicaCount: 1
  image:
    repository: acrsubneterdev.azurecr.io/react
    tag: latest
  containerPort: 5173
  service: 
    type: ClusterIP
    port: 80
