apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}-ingress
  namespace: {{ .Values.app.name }}
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  tls:
  - hosts:
    - subnete.de
    secretName: subneter
  rules:
  - http:
      paths:
      - backend:
          service:
            name: {{ .Values.react.name }}-service
            namespace: {{ .Values.app.name }}
            port:
              number: {{ .Values.react.service.port }}  
        path: /
        pathType: Prefix
      - backend:
          service:
            name: {{ .Values.flask.name }}-service
            namespace: {{ .Values.app.name }}
            port:
              number: {{ .Values.flask.service.port }}  
        path: /api
        pathType: Prefix
  volumes:
    - name: {{ $.Values.app.name }}-secretproviderclass
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: {{ $.Values.app.name }}-secretproviderclass