# Generated by Django 5.0.4 on 2024-06-12 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subnet',
            old_name='mask',
            new_name='subnetmask',
        ),
        migrations.RemoveField(
            model_name='vnet',
            name='size',
        ),
        migrations.RemoveField(
            model_name='vnet',
            name='startip',
        ),
        migrations.CreateModel(
            name='AddressSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('networkaddress', models.CharField(max_length=255)),
                ('subnetmask', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addressspaces', to='calculator_app.vnet')),
            ],
        ),
    ]
