name: Build and Push Docker images

on:
  workflow_dispatch:

  push:
    paths:
      - "**.backend"
      - "**.frontend"

  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name ${{ vars.ACR_NAME }}

      - name: Build and Push React Frontend Docker Image
        run: |
          docker build -t ${{ vars.AZURE_REGISTRY_SERVER }}/react:latest ${{ vars.FRONTEND_PATH }}
          docker push ${{ vars.AZURE_REGISTRY_SERVER }}/react:latest

      - name: Build and Push Flask Backend Docker Image
        run: |
          docker build -t ${{ vars.AZURE_REGISTRY_SERVER }}/django:latest ${{ vars.BACKEND_PATH }}
          docker push ${{ vars.AZURE_REGISTRY_SERVER }}/django:latest
