name: deploy-infra

on:
  workflow_dispatch:

  push:
  
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: v1.7.5

      - name: Install TFlint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Terraform Init
        run: terraform init
        working-directory: ./infrastructure/terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./infrastructure/terraform

      - name: Terraform Format
        run: terraform fmt -check -recursive
        working-directory: ./infrastructure/terraform
      
      #- name: Run Checkov action
      #  id: checkov
      #  uses: bridgecrewio/checkov-action@master
      #  with: 
      #    framework: terraform
      
      - name: Terraform Plan
        id: tf-plan
        run: terraform plan -out plan.infra
        working-directory: ./infrastructure/terraform
         
      - name: Publish Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan
      
      - name: Publish Terraform Plan to Task Summary
        env:
          SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
        run: |
          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
      
      - name: Download Terraform Plan
        uses: actions/download-artifact@v3
        with:
          name: tfplan
    
        # Terraform Apply
      - name: Terraform Apply
        run: terraform apply tfplan
          