name: deploy-infra

#Stage Param setzen

on:
  workflow_dispatch:

  push:
  
  pull_request:
    branches:
      - main

env:
  ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Install Terraform"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: "Install TFlint"
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Format
        run: terraform fmt -check -recursive
      
      # Perform a security scan of the terraform code using checkov
      - name: Run Checkov action
        id: checkov
        uses: ov/checkov-action@master
        with: 
          framework: terraform
      
      - name: Terraform Plan
        run: terraform plan -chdir=./infrastructure/terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -chdir=./infrastructure/terraform apply -auto-approve tfplan
        